server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

logging:
  loggers:
    io.cratekube: DEBUG
    org.reflections: ERROR

swagger:
  resourcePackage: io.cratekube.lifecycle.resources

jerseyClient:
  timeout: 5000ms
  gzipEnabledForRequests: false

auth:
  apiKeys:
    - name: admin
      key: ${ADMIN_APIKEY:-eknvDrmcDtseeieSMTvngo}
      roles: ['admin']

kubeconfigLocation: ${KUBE_CONFIG_LOCATION:-/app/kube/internal-config}

jobs:
  upgradeAvailabilityJob: ${JOB_EXECUTION_FREQUENCY:-10min}

managedComponents:
  cluster-mgmt-service: https://github.com/cratekube/cluster-mgmt-service/releases.atom
  cloud-mgmt-service: https://github.com/cratekube/cloud-mgmt-service/releases.atom
  lifecycle-service: https://github.com/cratekube/lifecycle-service/releases.atom
  # k8s yaml 'template' files will contain an 'annotation' for version.
  # whatever this key is should coincide with top level k8s resource name for retrieval purposes
  # lifecycle-service template needs to account for deploying itself
